services:
    Enhavo\Bundle\ResourceBundle\Action\ActionManager:
        arguments:
            - '@security.authorization_checker'
            - '@Enhavo\Component\Type\FactoryInterface[Action]'

    Enhavo\Bundle\ResourceBundle\Action\Type\BaseActionType:
        arguments:
            - '@translator'
            - '@Enhavo\Bundle\ResourceBundle\ExpressionLanguage\ResourceExpressionLanguage'
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\ResourceBundle\Action\Type\UrlActionType:
        arguments:
            - '@router'
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\ResourceBundle\Action\Type\SaveActionType:
        arguments:
            - '@router'
        tags:
            - { name: enhavo.action }