services:
    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceIndexEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Grid\GridFactory'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceListEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Grid\GridFactory'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceCreateEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Input\InputFactory'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }

    Enhavo\Bundle\ResourceBundle\Endpoint\Type\ResourceUpdateEndpointType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Input\InputFactory'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: enhavo_api.endpoint }
            - { name: container.service_subscriber }