services:
    Enhavo\Bundle\ResourceBundle\Filter\FilterManager:
        arguments:
            - '@security.authorization_checker'
            - '@Enhavo\Component\Type\FactoryInterface[Filter]'

    Enhavo\Bundle\ResourceBundle\Filter\FilterQueryFactory:
        arguments:
            - '@doctrine.orm.entity_manager'

    Enhavo\Bundle\ResourceBundle\Filter\Type\AgeFilterType:
        tags:
            - { name: enhavo_resource.filter }

    Enhavo\Bundle\ResourceBundle\Filter\Type\AutoCompleteEntityType:
        arguments:
            - '@router'
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
        tags:
            - { name: enhavo_resource.filter }

    Enhavo\Bundle\ResourceBundle\Filter\Type\BaseFilterType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\ExpressionLanguage\ResourceExpressionLanguage'
            - '@translator'
        tags:
            - { name: enhavo_resource.filter }

    Enhavo\Bundle\ResourceBundle\Filter\Type\BetweenFilterType:
        arguments:
            - '@translator'
        tags:
            - { name: enhavo_resource.filter }

    Enhavo\Bundle\ResourceBundle\Filter\Type\BooleanType:
        arguments:
            - '@translator'
        tags:
            - { name: enhavo_resource.filter }

    Enhavo\Bundle\ResourceBundle\Filter\Type\DateBetweenFilterType:
        tags:
            - { name: enhavo_resource.filter }

    Enhavo\Bundle\ResourceBundle\Filter\Type\EntityType:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'
        tags:
            - { name: enhavo_resource.filter }

    Enhavo\Bundle\ResourceBundle\Filter\Type\OptionType:
        arguments:
            - '@translator'
        tags:
            - { name: enhavo_resource.filter }

    Enhavo\Bundle\ResourceBundle\Filter\Type\TextType:
        tags:
            - { name: enhavo_resource.filter }
