services:
    Enhavo\Bundle\ResourceBundle\Input\Input:
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: 'container.service_subscriber' }
            - { name: 'enhavo_resource.input' }

    Enhavo\Bundle\ResourceBundle\Input\InputFactory:
        arguments:
            - '%enhavo_resource.inputs%'
